config/routes.rb
  Carepoints::Application.routes.draw do
  root 'pages#home'  
  resources :users do
    resources :cares 
    resource :histories, only: [:create]
  end
  

  resource :session, only: [:new, :create, :destroy] # creates 3 routes instead of 8 -- omits index

  
  get 'users/:id/reactivate' => 'users#reactivate', as: :reactivate
  patch 'users/:id/reactivate' => 'users#reactivate', as: :reactivate_user
  post 'users/:id/reactivate' => 'users#reactivate'

  get 'pages/contact' => 'pages#contact'
  get 'pages/about' => 'pages#about'
  get 'pages/examples' => 'pages#examples'
  get 'pages/howto' => 'pages#howto'

end

app/models/care.rb
class Care
  include Mongoid::Document 
  field :care_item, type: String
  field :value, type: Integer

  validates_presence_of :care_item, :value
  validates_numericality_of :value
  
  embedded_in :user, :inverse_of => :cares
  
end

app/models/history.rb
class History
  include Mongoid::Document
  field :date, type: Date
  field :care_item, type: String
  field :value, type: Integer

  embedded_in :user, :inverse_of => :histories
 
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :name, type: String
  field :email, type: String
  field :points, type: Integer
  field :password_digest, type: String
  field :is_active, type: Mongoid::Boolean, default: true
  validates_presence_of :name, :email, :password_digest
  validates_uniqueness_of :email
  
  has_secure_password

  embeds_many :cares
  embeds_many :histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

end

app/controllers/cares_controller.rb
class CaresController < ApplicationController
	
	def create
		@user = User.find(params[:user_id])
		user_care = @user.cares.new(params.require(:care).permit(:care_item, :value))
		if user_care
			user_care.save
			redirect_to @user
		end
	end

	def edit
		@user = User.find(params[:user_id])
		@care = @user.cares.find(params[:id])
	end

	def update
		@user = User.find(params[:user_id])
		@care = @user.cares.find(params[:id])
		@care.update_attributes(params.require(:care).permit(:care_item, :value))
		redirect_to user_path(params[:user_id])
	end

	def destroy	
		@user = User.find(params[:user_id])
		@care = @user.cares.find(params[:id]).delete
		redirect_to @user
	end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController

	def create
		@user = User.find(params[:user_id])
		user_history = @user.histories.new(params.require(:history).permit(:date, :care_item, :value))
		if user_history.save
			redirect_to @user
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController	

end	

app/controllers/sessions_controller.rb
	class SessionsController < ApplicationController
	def new
		# present an empty login form
		@user = User.new
		@is_login = true
	end

	def create
		#find the user who's trying to login
		u = User.where(email: params[:user][:email]).first
		if u && u.authenticate(params[:user][:password])
			if u.is_active == false
				redirect_to reactivate_path(u.id)	
			else
			# store as a cookie in the users' browser the ID of them, indicating they're logged in
				session[:user_id] = u.id.to_s
				redirect_to user_path(u.id)
			end
		else
			#go back to the login page
			redirect_to new_session_path
		end
	end

	def destroy
		reset_session
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
		@users = User.where(is_active: true)
	end

	def new
		@user = User.new		
	end	

	def create
		@user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
		if @user.save
	  	#create a new session, thereby logging in the new user
	  	u = User.where(email: params[:user][:email]).first
	  	session[:user_id] = u.id.to_s
			redirect_to user_path(u.id)
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if current_user != @user
			if current_user
				redirect_to user_path(current_user)
			elsif @user.is_active == false
				@user.update_attributes(params.require(:user).permit(:is_active))
				u = User.find(params[:id])
				session[:user_id] = u.id.to_s
				redirect_to user_path(u.id)	
			else 
				redirect_to new_session_path
			end
		elsif @user.update_attributes(params.require(:user).permit(:name, :email, :is_active))
			redirect_to user_path
		else 
			render :edit	
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.is_active = false
		@user.save
		#destroy session so user is automatically logged out
		reset_session
		redirect_to root_path
	end

	def reactivate
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cares_helper.rb
module CaresHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cares/edit.html.erb
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<h1>Edit this care</h1>
		<%= form_for [@user, @care] do |f| %>
			<div class="form-group">
				<%= f.text_field :care_item, placeholder: "Care Item", class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.text_field :value, placeholder: "Value", class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.submit "Submit", class: 'btn btn-primary btn-large btn-block' %>
			</div>
		<% end %>
		
		<div class="form-group">
		<%= button_to "Delete this care", user_care_path, method: :delete, data: { confirm: 'Are you sure you want to delete this care?' }, class: 'btn btn-danger btn-large btn-block' %>
		</div>
		
		<div class="text-center">
			<%= link_to "Back to your profile", user_path(params[:user_id]), class: 'btn btn-warning btn-large btn-block' %>
		</div>
	</div>	
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Care Points</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to 'Home', root_path %> </li>
        <li><%= link_to 'About', pages_about_path %> </li>
        <li><%= link_to 'Contact', pages_contact_path %> </li>
        <% if current_user %>
          <li> <%= link_to 'My Profile', user_path(current_user) %> </li>
        <% end %>   
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">
            Welcome, <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li> 
                <!-- This is the Edit User Link -->
                <%= link_to 'Edit Profile', edit_user_path(current_user) %>
              </li>
              <li>
                <%= link_to 'Log out', session_path, method: :delete %>
              </li>
              <li>
                <%= link_to 'How to', pages_howto_path %>
              </li>
              <li>
                <!-- This is the Delete User Account Link-->
                <%= link_to "Delete Account", user_path(current_user), method: :delete, data: { confirm: 'Are you sure you want to delete your profile?'} %>
              </li>
          </ul>
        </li>
        <% else %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">
              Log in
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to 'Log in', new_session_path  %> 
              </li>
              <li>
                <%= link_to 'Sign up', new_user_path %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Care Points</title>
 
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- nav bar partial -->
	<%= render 'layouts/nav' %>


  <%= yield %>
  <!--pages render here -->
</body>
</html>

app/views/pages/about.html.erb
<div class="container-fluid">
	<div class="row well well-lg">
		<div class="col-md-6 col-md-offset-4">
			<p class="lead text-left ">Do you ever find yourself <mark>overwhelmed</mark>?<br/>Too much to do and not enough time?<br/> No matter how hard you try, you can never catch up?<br/> Most life coaches and self-help "experts" will try to teach you tips and tricks to help you juggle all of the demands on your time.<br/>But we think there's a better way!<br/>Instead of managing your time, we believe you should <mark>manage your care</mark>.<br/>Using the Care Points method helps you see clearly how much you care about the things in your life and to identify where you should adjust your care, or even not care at all.<br/>Curious about what you should care?
			</p>
		</div>
	</div>
	<div class="row text-center">
		<%= link_to 'Show me some Cares', pages_examples_path, class: 'btn btn-info btn-md' %>
	</div>
</div>

app/views/pages/contact.html.erb
<div class="container-fluid">
	<div class="row">
	    <div class="col-md-4 col-md-offset-5">
				<!-- <div class="alert alert-success"><strong>Success! Message sent. (If form ok!)</strong></div>	  
			   <div class="alert alert-danger"><strong> Error! Please check the inputs. (If form error!)</strong></div>
			  </div>  -->
			  <h1>Contact Us</h1><br/><br/>
	  		<form role="form" action="" method="post" >
	    		<div >
			      <div class="form-group">
			        <label for="InputName">Your Name</label>
			        <div class="input-group">
			          <input type="text" class="form-control" name="InputName" id="InputName" placeholder="Enter Name" required>
			        </div>
			      </div>
			      <div class="form-group">
			        <label for="InputEmail">Your Email</label>
			        <div class="input-group">
			          <input type="email" class="form-control" id="InputEmail" name="InputEmail" placeholder="Enter Email" required >
			         </div>
			      </div>
			      <div class="form-group">
			        <label for="InputMessage">Message</label>
			        <div class="input-group">
			          <textarea name="InputMessage" id="InputMessage" class="form-control" rows="5" required></textarea>
			        </div>
			      </div>

	      		<input type="submit" name="submit" id="submit" value="Submit" class="btn btn-info disabled">
	    		</div>
	  		</form>
	  	</div>
	  </div>
	</div>
</div>
 

app/views/pages/examples.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			
			<table class="table table-striped table-bordered table-hover">
				<tr>
					<td>Drinking</td>
					<td>40 Care Points</td>
				</tr>
				<tr>
					<td>Sitting in traffic</td>
					<td>100 Care Points</td>
				</tr>
				<tr>
					<td>Entertaining house guests</td>
					<td>80 Care Points</td>
				</tr>
				<tr>
					<td>Doing homework</td>
					<td>70 Care Points</td>
				</tr>
				<tr>
					<td>Cleaning bathroom</td>
					<td>40 Care Points</td>
				</tr>
				<tr>
					<td>Mashing potatoes</td>
					<td>10 Care Points</td>
				</tr>
				<tr>
					<td>Working out</td>
					<td>60 Care Points</td>
				</tr>
				<tr>
					<td>Learning a new instrument</td>
					<td>5 Care Points</td>
				</tr>
				<tr>
					<td>Javascript</td>
					<td>15 Care Points</td>
				</tr>
				<tr>
					<td>Weddings</td>
					<td>85 Care Points</td>
				</tr>
				<tr>
					<td>Moving to a new city</td>
					<td>95 Care Points</td>
				</tr>
				<tr>
					<td>Presentations</td>
					<td>55 Care Points</td>
				</tr>
			</table>
			<div class="row text-center">
				<%= link_to "Why not sign up?", new_user_path, class: 'btn btn-info btn-md' %>
			</div>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="container theme-showcase" role="main">
  <!-- Main jumbotron-->
  <div class="jumbotron">
	  <h1>Welcome to Care Points!</h1>
	  <p>See what you really care about using our patented point system. We believe that your life will be deeply enriched by focusing on what you care about. Use our care point system to track your cares every day. There's no good reason not to start using them now.</p>
    <a class="btn btn-primary btn-lg" role="button" <%= link_to 'Sign up »', new_user_path %>
   	</a>
  </div>
</div>

		

app/views/pages/howto.html.erb
<div class="container-fluid">
	<div class="col-lg-12">
		<h1 class="text-center">How to get started:
		<h1>
		<div class="row">
			<div class="col-lg-8 col-lg-offset-3">
				<ol class="lead">
					<li>Enter some cares and values...at least 1000 points to start.
					</li>
					<li>Check your daily care allowance to see how much you can care each day.
					</li>
					<li>Before you care about something, see whether you have enough points.
					</li>
					<li>Click the 'care about this' button and watch your daily total decrease.
					</li>
					<li>You can only care about things for which you have enough points.
					</li>
					<li>You can add to your care list at any time. 
					</li>
					<li>Your daily points are recycled each day.
					</li>
					<li>Care metrics coming soon! 
					</li>
				</ol>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<h1>Edit your profile</h1>
		<%= form_for @user do |f| %>
		<div class="form-group">
			<%= f.text_field :name, placeholder: "Name", class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.text_field :email, placeholder: "Email", class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit "Submit", class: 'btn btn-primary btn-large btn-block' %>
		</div>
		<% end %>
		<div class="text-center">
			<%= link_to "Back to your profile", user_path, class: 'btn btn-warning btn-large btn-block' %>
		</div>
	</div>	
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
	<% @users.each do |u| %>
		<li>
		Name: <%= u.name %><br/>
		Email: <%= u.email %> <br/>
	  </li>
	  <br/>
<% end %>
</ul>

<!-- This will be an admin only page -->

app/views/users/new.html.erb
<%= form_for @user, html: { class: 'form' } do |f| %>
	<% if @user.errors.any? %>
		<div class="row">
				<div class="col-sm-4 col-sm-offset-4" id="error_explanation">
		      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being signed up:</h2>
		      <ol>
			      <% @user.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			    </ol>
		    </div>
		</div>
	<% end %>
		

	<div class="row">
		<div class="col-sm-4 col-sm-offset-4">
			<h1> Sign up for Care Points!</h1>
			<%= form_for @user do |f| %>
				<div class="form-group">
					<%= f.text_field :name, placeholder: "Name", class: 'form-control', required: true %>
				</div>
				<div class="form-group">
					<%= f.text_field :email, placeholder: "Email", class: 'form-control', required: true %>
				</div>
				<div class="form-group">
					<%= f.password_field :password, placeholder: "Password", class: 'form-control', required: true %>
				</div>
				<div class="form-group">
					<%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form-control', required: true %>
				</div>
				<div class="form-group">
					<%= f.submit "Sign up", class: 'btn btn-primary btn-large'%>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

app/views/users/profile.html.erb
<h1>Set up your care point system here.</h1>
<%= form_for @user do |f| %>
	<%= f.text_field :name, placeholder: "Name" %>
	<%= f.text_field :email, placeholder: "Email" %>
	<%= f.submit "Submit this" %>
<% end %>

app/views/users/reactivate.html.erb
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<h1>So, you miss your Care Points?</h1>
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.hidden_field :is_active, :value => true, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.submit "Reactivate my account", class: 'btn btn-primary btn-large btn-block' %>
			</div>
		<% end %>
	</div>	
</div>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="row">
		<h1 class="text-center"> <%= @user.name %>'s Profile Page </h1>
	</div>
	<div class="row">
		<div class="col-md-5 col-md-offset-1">
		  <!-- This is the display of a User's Daily Care Points-->
			<% value_sum = 0 %>
			<% @user.cares.each do |u| %>
				<% value_sum += u.value %>
			<% end %>
			<% (value_sum -= (value_sum * 0.3)).to_i %>
			<% @user.histories.each do |u| %>
				<% if Date.today == u.date %>
					<% value_sum -= u.value %>
				<% end %>
			<% end %>
			<!-- This is the running display of a User's Cares-->
			<h2> These are your Cares: </h2> 
			<ul class="well well-sm list-unstyled">
				<% @user.cares.each do |u| %>
					<li class="lead"> 
						<%= u.care_item %>, worth <%= u.value %> care points 				
						<!-- calculation -->
						<% if value_sum+1 <= u.value %>
							<% disable_care = true %>
						<% end %>
						<!-- This Button populates the User Histories -->
						<%= form_for [@user, History.new] do |f| %>
							<%= f.hidden_field :date, :value => Date.today %>
							<%= f.hidden_field :care_item, :value => u.care_item %>
							<%= f.hidden_field :value, :value => u.value %>
							<!--button action -->
							<% if disable_care == true %>				
								<%= f.submit 'Care About This!', disabled: true, class: 'btn btn-warning btn-md' %>
							<% else %>
								<%= f.submit 'Care About This!', disabled: false, class: 'btn btn-warning btn-md' %>
							<% end %>
						<% end %>			
						<!-- This is the Edit This Care Button -->
						<%= link_to "Edit this care", edit_user_care_path(params[:id], u.id, method: :patch), class: 'btn btn-info btn-md' %>			
					</li>
				  <br/>
				<% end %>
			</ul>
	    <!-- This is the form for entering Cares -->	
			<h2>Enter a new care</h2>
			<%= form_for [@user, Care.new] do |f| %>
				<div class="form-group">
					<%= f.text_field :care_item, placeholder: "Enter your care here", class: 'form-control', required: true %>
				</div>
				<div class="form-group">
					<%= f.text_field :value, placeholder: "Enter your care's value", class: 'form-control', required: true %>
				</div>
				<div class="form-group">
					<%= f.submit "Submit", class: 'btn btn-primary btn-large btn-block' %>
				</div>
			<% end %>
		</div>
		<div class="col-md-5">
			<!-- This is the Current Daily Care Points total -->
			<h2> 
				<% if value_sum <= 0 %>
					<%= "You have 0 care points left for the day..." %>
				<% else %>
					<%= "You Have " + value_sum.to_i.to_s + " Care Points Left for the Day" %>
				<% end %>	
			</h2>
		  <!-- Iterates through the User's History by Current Date -->
			<h2>These are <%= @user.name %>'s Cares Today:
			</h2>
			<ul>
				<% @user.histories.each do |u| %>
					<% if u.date == Date.today %>
						<li class="lead"> <%= u.care_item %></li>
					<% end %>
				<% end %>
			</ul>
		</div>
	</div>
</div>